services:
  steplogweb:
    build:
      context: .
      dockerfile: ./services/DockerfileWeb
      args:
        PHP_ENV: ${PHP_ENV}
    container_name: steplogweb
    networks:
      - my-network
    depends_on:
      - steplogdb
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html/
    restart: always
  steplogdb:
    build:
      context: .
      dockerfile: ./services/DockerfileDB
    networks:
      - my-network
    container_name: steplogdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    restart: always
networks:
  my-network: